version: 2
jobs:
  test:
    working_directory: ~/actions
    docker:
      - image: rayriffy/yarn:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Update Alpine
          command: |
            apk update
      - run:
          name: Test file
          command: |
            yarn
            yarn test
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: rayriffy/yarn:latest
    working_directory: ~/actions
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Update Alpine
          command: |
            apk update
      - run:
          name: Build file
          command: |
            yarn
            yarn build
      - save_cache:
          key: dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
  deploy:
    machine:
        enabled: true
    working_directory: ~/actions
    steps:
      - restore_cache:
          keys:
            - dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Update Alpine
          command: |
            apk update
      - add_ssh_keys:
          fingerprints:
            - "7a:64:ff:ff:10:61:8f:f5:22:9a:60:d7:f9:d9:62:93"
      - run:
          name: Get rayriffy-com repo
          command: |
            git clone git@gitlab.com:rayriffy/rayriffy-com.git
            cd rayriffy-com/web/data/node
            mkdir ~/tmp
            rm -rf maimaibotaog.rayriffy.com
      - run:
          name: Get Code
          command: |
            mv ~/actions/dist rayriffy-com/web/data/node/maimaibotaog.rayriffy.com
      - run:
          name: Push
          command: |
            cd rayriffy-com/web/data/node/maimaibotaog.rayriffy.com
            git config --global user.name "Autobot"
            git config --global user.email bot@rayriffy.com
            git add .
            git commit -m "[AUTO] maimaibotaog.rayriffy.com Deploy Triggered"
            git push origin master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - release
      - deploy:
          requires:
            - test
            - build
          filters:
            branches:
              only: release