version: 2
jobs:
  build:
    working_directory: ~/actions
    docker:
      - image: rayriffy/yarn:latest
        environment:
          DEPLOY_HOST: $DEPLOY_HOST
    steps:
      - checkout
      - run:
          name: Update Alpine
          command: |
            apk update
      - run:
          name: Install Node packages
          command: |
            yarn
            yarn global add jshint
      - run:
          name: Test file
          command: |
            yarn test
      - run:
          name: Build file
          command: |
            yarn build
  deploy:
    machine:
        enabled: true
    working_directory: ~/actions
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c7:29:52:e0:f0:33:ca:91:1b:30:3a:96:1f:34:a7:fd"
      - run:
          name: Deploy Server
          command: |
            ssh -i ~/.ssh/id_rsa_c72952e0f033ca911b303a961f34a7fd $DEPLOY_HOST 'cd ~/production/actions-on-google && pm2 stop 0 && git pull && yarn && yarn build && pm2 start 0'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release